export interface ExerciseSeed {
  name: string;
  category: string;
  equipment: string;
  defaultVideoUrl: string | null;
}

export interface TemplateSeed {
  name: string;
  mesoType: number;
  days: { dayNumber: number; exerciseNames: string[] }[];
}

export const exercises: ExerciseSeed[] = [
  { name: "High Bar Squat", category: "QUADS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/Y_M50iyrd3U" },
  { name: "Leg Press", category: "QUADS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/B6rGDcfyPto" },
  { name: "Hack Squat", category: "QUADS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/lKDKzajdcjA" },
  { name: "Leg Extension", category: "QUADS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/KDDwcS2PBYM" },
  { name: "Front Squat", category: "QUADS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/v-mQm_droHg" },
  { name: "Dumbbell Goblet Squat", category: "QUADS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/lrqtGXD32FA" },
  { name: "Dumbbell Bulgarian Split Squat", category: "QUADS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/hiLF_pF3EJM" },
  { name: "Dumbbell Lunges", category: "QUADS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/Z6R8A5tcrTc" },
  { name: "Bodyweight Sissy Squat", category: "QUADS", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/n5WeYzi7Dqo" },
  { name: "Dumbbell Step Ups", category: "QUADS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/aKj-6hgiViA" },
  { name: "Barbell Hip Thrust", category: "GLUTES", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/kqi4_EPpwCk" },
  { name: "Barbell Romanian Deadlift", category: "GLUTES", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/uhghy9pFIPY" },
  { name: "Cable Pull Through", category: "GLUTES", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/OkcryKUZTZs" },
  { name: "Hip Abduction Machine", category: "GLUTES", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/h9BqUMqK-SY" },
  { name: "Dumbbell Hip Thrust", category: "GLUTES", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/29OfN4ztW_g" },
  { name: "Dumbbell Romanian Deadlift", category: "GLUTES", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/gW-7wKSAhEY" },
  { name: "Bodyweight Glute Bridge", category: "GLUTES", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/evOnUDkq9f4" },
  { name: "Dumbbell Sumo Deadlift", category: "GLUTES", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/De9OUZz5W_I" },
  { name: "Lying Leg Curl", category: "HAMSTRINGS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/PXG69tKDHoc" },
  { name: "Seated Leg Curl", category: "HAMSTRINGS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/S367qaHeYWU" },
  { name: "Barbell Stiff Leg Deadlift", category: "HAMSTRINGS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/CN_7cz3P-1U" },
  { name: "Glute Ham Raise", category: "HAMSTRINGS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/DUbfV3DADcg" },
  { name: "Dumbbell Stiff Leg Deadlift", category: "HAMSTRINGS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/ymL6b50Al6U" },
  { name: "Dumbbell Single Leg Deadlift", category: "HAMSTRINGS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/vwbYrwrF8fM" },
  { name: "Bodyweight Nordic Curl", category: "HAMSTRINGS", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/_e9vFU9-tkc" },
  { name: "Dumbbell Lying Leg Curl", category: "HAMSTRINGS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/ZHlBSI6JPsA" },
  { name: "Medium Grip Bench Press", category: "HORIZONTAL PUSH", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/A0NBCkpYatQ" },
  { name: "Machine Chest Press", category: "HORIZONTAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/SUdQ1roIWz0" },
  { name: "Cable Fly", category: "HORIZONTAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/kEDraCFRgrI" },
  { name: "Pec Deck Machine", category: "HORIZONTAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/hZ0CGRaKwbQ" },
  { name: "Dumbbell Flat Bench Press", category: "HORIZONTAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/Vb0SyK9HEFQ" },
  { name: "Dumbbell Fly", category: "HORIZONTAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/eozdVDA78K0" },
  { name: "Bodyweight Push Up", category: "HORIZONTAL PUSH", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/GgwGk6QvAJ0" },
  { name: "Dumbbell Squeeze Press", category: "HORIZONTAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/f0hOKO_eD-Q" },
  { name: "Smith Machine Bench Press", category: "HORIZONTAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/O5viuEPDXKY" },
  { name: "Incline Barbell Bench Press", category: "INCLINE PUSH", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/wqByyWZjHgY" },
  { name: "Incline Machine Press", category: "INCLINE PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/0f6-uCUKqgA" },
  { name: "Low to High Cable Fly", category: "INCLINE PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/KFl3Re5UbPo" },
  { name: "Dumbbell Incline Bench Press", category: "INCLINE PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/5CECBjd7HLQ" },
  { name: "Dumbbell Incline Fly", category: "INCLINE PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/idAvu2HvqSQ" },
  { name: "Bodyweight Incline Push Up", category: "INCLINE PUSH", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/76TQU7iZlsI" },
  { name: "Standing Barbell Shoulder Press", category: "VERTICAL PUSH", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/GGpArq725ls" },
  { name: "Seated Barbell Shoulder Press", category: "VERTICAL PUSH", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/IuzRCN6eG6Y" },
  { name: "Machine Shoulder Press", category: "VERTICAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/3R14MnZbcpw" },
  { name: "Machine Lateral Raise", category: "LATERAL DELTS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/n5dsI9qQXwY" },
  { name: "Cable Lateral Raise", category: "LATERAL DELTS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/lq7eLC30b9w" },
  { name: "Dumbbell Shoulder Press", category: "VERTICAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/HzIiNhHhhtA" },
  { name: "Dumbbell Lateral Raise", category: "LATERAL DELTS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/4hTUCDUQaNA" },
  { name: "Dumbbell Arnold Press", category: "VERTICAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/ris9tKqMwgU" },
  { name: "Bodyweight Pike Push Up", category: "VERTICAL PUSH", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/RmKUhj62_9c" },
  { name: "Barbell Bent Over Row", category: "HORIZONTAL BACK", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/7B5Exks1KJE" },
  { name: "Seated Cable Row", category: "HORIZONTAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/UCXxvVItLoM" },
  { name: "T-Bar Row", category: "HORIZONTAL BACK", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/SbZycT7Eq58" },
  { name: "Machine Row", category: "HORIZONTAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/GIX5qMzh9iQ" },
  { name: "Chest Supported Row Machine", category: "HORIZONTAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/bmWA2yO9Aa0" },
  { name: "Dumbbell Single Arm Row", category: "HORIZONTAL BACK", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/k2kVniB5eQI" },
  { name: "Dumbbell Bent Over Row", category: "HORIZONTAL BACK", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/p9RihhjmJsw" },
  { name: "Bodyweight Inverted Row", category: "HORIZONTAL BACK", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/KOaCM1HMwU0" },
  { name: "Dumbbell Seal Row", category: "HORIZONTAL BACK", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/49Hbk_5fhoI" },
  { name: "Normal Grip Pulldown", category: "VERTICAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/VXKfH6ciEBI" },
  { name: "Wide Grip Pulldown", category: "VERTICAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/YCKPD4BSD2E" },
  { name: "Close Grip Pulldown", category: "VERTICAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/6FEIuXBCtR4" },
  { name: "Straight Arm Pulldown", category: "VERTICAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/G9uNaXGTJ4w" },
  { name: "Bodyweight Pull Up", category: "VERTICAL BACK", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/s5hluoQjtIM" },
  { name: "Bodyweight Chin Up", category: "VERTICAL BACK", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/e1YSApl-QcM" },
  { name: "Dumbbell Pullover", category: "VERTICAL BACK", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/Cvsaj2AXevI" },
  { name: "Bodyweight Lat Pulldown (Band)", category: "VERTICAL BACK", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/SNiwpA13ZLU" },
  { name: "Barbell Curl", category: "BICEPS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/QZEqB6wUPxQ" },
  { name: "EZ Bar Curl", category: "BICEPS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/tJIFTI9wZOw" },
  { name: "Cable Curl", category: "BICEPS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/ue06dNcMjeY" },
  { name: "Preacher Curl Machine", category: "BICEPS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/AR-oARBkYxI" },
  { name: "Dumbbell Bicep Curl", category: "BICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/XE_pHwbst04" },
  { name: "Dumbbell Hammer Curl", category: "BICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/8XLxfXROrTo" },
  { name: "Dumbbell Incline Curl", category: "BICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/L9nnbFzdl3Y" },
  { name: "Dumbbell Concentration Curl", category: "BICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/Jvj2wV0vOYU" },
  { name: "Close Grip Bench Press", category: "TRICEPS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/Cv5nS1AH_jE" },
  { name: "Cable Tricep Pushdown", category: "TRICEPS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/6Fzep104f0s" },
  { name: "Cable Overhead Tricep Extension", category: "TRICEPS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/1u18yJELsh0" },
  { name: "Tricep Dip Machine", category: "TRICEPS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/EBnq0A5L_wo" },
  { name: "Dumbbell Overhead Tricep Extension", category: "TRICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/v1qDINLCb8Q" },
  { name: "Dumbbell Skull Crusher", category: "TRICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/8t2a93BjDec" },
  { name: "Dumbbell Kickback", category: "TRICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/XuH2W_R5YoA" },
  { name: "Bodyweight Diamond Push Up", category: "TRICEPS", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/J0DnG1_S92I" },
  { name: "Dips", category: "TRICEPS", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/Tw0axi-Jlqc" },
  { name: "Calves on Leg Press", category: "CALVES", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/avUN5U2Whzc" },
  { name: "Single Leg Dumbbell Calf Raise", category: "CALVES", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/uhLjADhUxFM" },
  { name: "Standing Calf Raise", category: "CALVES", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/KVZ3qtJA4AU" },
  { name: "Seated Calf Raise", category: "CALVES", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/smyXy_dhXo8" },
  { name: "Barbell Shrug", category: "TRAPS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/zfAHfyTB_Ao" },
  { name: "Dumbbell Shrug", category: "TRAPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/SX1FE0URdv8" },
  { name: "Cable Facepull", category: "REAR DELTS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/0Po47vvj9g4" },
  { name: "Dumbbell Rear Lateral Raise", category: "REAR DELTS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/J45NrrYB5ms" },
  { name: "Reverse Pec Deck", category: "REAR DELTS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/gT5sh9_56Vc" },
  { name: "Machine Crunch", category: "ABS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/0kLWho-pEdQ" },
  { name: "Cable Crunch", category: "ABS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/6GMKPQVERzw" },
  { name: "Hanging Leg Raise", category: "ABS", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/q6pqNDXmvIU" },
  { name: "Conventional Deadlift", category: "GLUTES", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/VL5Ab0T07e4" },
  { name: "Sumo Deadlift", category: "GLUTES", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/XsrD5y8EIKU" },
  { name: "Barbell Walking Lunge", category: "QUADS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/X9QswJmhBQI" },
  { name: "45 Degree Back Raise", category: "HAMSTRINGS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/5_ejbGfdAQE" },
  { name: "Underhand Pulldown", category: "VERTICAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/PLjlB4A89zg" },
  { name: "Cable Upright Row", category: "LATERAL DELTS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/V3h_1IUY-f0" },
  { name: "Dumbbell Twist Curl", category: "BICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/wL85MrmoCLc" },
];

export const templates: TemplateSeed[] = [
  {
    name: "The Thor Specialization",
    mesoType: 5,
    days: [
      { dayNumber: 1, exerciseNames: ["Incline Barbell Bench Press", "Dumbbell Fly", "Barbell Bent Over Row", "Normal Grip Pulldown"] },
      { dayNumber: 2, exerciseNames: ["Standing Barbell Shoulder Press", "Dumbbell Lateral Raise", "Dumbbell Skull Crusher", "Dumbbell Hammer Curl"] },
      { dayNumber: 3, exerciseNames: ["High Bar Squat", "Leg Press", "Seated Leg Curl", "Calves on Leg Press"] },
      { dayNumber: 4, exerciseNames: ["Cable Fly", "Underhand Pulldown", "Cable Upright Row", "Cable Tricep Pushdown", "Barbell Curl"] },
      { dayNumber: 5, exerciseNames: ["Dumbbell Lateral Raise", "Barbell Shrug", "Dumbbell Twist Curl", "Dips"] },
    ],
  },
  {
    name: "The Valkyrie (Glute Specialization)",
    mesoType: 5,
    days: [
      { dayNumber: 1, exerciseNames: ["Conventional Deadlift", "Barbell Walking Lunge", "Dumbbell Hip Thrust", "Seated Leg Curl"] },
      { dayNumber: 2, exerciseNames: ["Medium Grip Bench Press", "Normal Grip Pulldown", "Standing Barbell Shoulder Press", "Bodyweight Push Up"] },
      { dayNumber: 3, exerciseNames: ["Hack Squat", "Dumbbell Bulgarian Split Squat", "45 Degree Back Raise", "Machine Crunch"] },
      { dayNumber: 4, exerciseNames: ["Seated Cable Row", "Cable Facepull", "Dumbbell Lateral Raise", "Dumbbell Rear Lateral Raise"] },
      { dayNumber: 5, exerciseNames: ["Sumo Deadlift", "Leg Press", "Lying Leg Curl", "Single Leg Dumbbell Calf Raise"] },
    ],
  },
  {
    name: "Arnold Split 6-Day",
    mesoType: 6,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Incline Barbell Bench Press", "Cable Fly", "Barbell Bent Over Row", "Normal Grip Pulldown"] },
      { dayNumber: 2, exerciseNames: ["Standing Barbell Shoulder Press", "Cable Lateral Raise", "Barbell Curl", "Cable Tricep Pushdown", "EZ Bar Curl"] },
      { dayNumber: 3, exerciseNames: ["High Bar Squat", "Leg Press", "Barbell Romanian Deadlift", "Lying Leg Curl", "Leg Extension"] },
      { dayNumber: 4, exerciseNames: ["Incline Barbell Bench Press", "Machine Chest Press", "Pec Deck Machine", "Seated Cable Row", "T-Bar Row"] },
      { dayNumber: 5, exerciseNames: ["Dumbbell Shoulder Press", "Machine Lateral Raise", "Dumbbell Hammer Curl", "Cable Overhead Tricep Extension", "Dumbbell Incline Curl"] },
      { dayNumber: 6, exerciseNames: ["Front Squat", "Hack Squat", "Barbell Stiff Leg Deadlift", "Seated Leg Curl", "Hip Abduction Machine"] },
    ],
  },
  {
    name: "Upper/Lower 4-Day",
    mesoType: 4,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Barbell Bent Over Row", "Dumbbell Shoulder Press", "Cable Curl", "Cable Tricep Pushdown"] },
      { dayNumber: 2, exerciseNames: ["High Bar Squat", "Lying Leg Curl", "Barbell Hip Thrust", "Leg Extension", "Standing Barbell Shoulder Press"] },
      { dayNumber: 3, exerciseNames: ["Incline Barbell Bench Press", "Normal Grip Pulldown", "Cable Fly", "EZ Bar Curl", "Cable Overhead Tricep Extension"] },
      { dayNumber: 4, exerciseNames: ["Leg Press", "Barbell Romanian Deadlift", "Seated Leg Curl", "Hip Abduction Machine", "Leg Extension"] },
    ],
  },
  {
    name: "Push/Pull/Legs 6-Day",
    mesoType: 6,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Incline Barbell Bench Press", "Standing Barbell Shoulder Press", "Cable Lateral Raise", "Cable Tricep Pushdown"] },
      { dayNumber: 2, exerciseNames: ["Barbell Bent Over Row", "Normal Grip Pulldown", "Seated Cable Row", "Barbell Curl", "Dumbbell Hammer Curl"] },
      { dayNumber: 3, exerciseNames: ["High Bar Squat", "Barbell Romanian Deadlift", "Leg Press", "Lying Leg Curl", "Leg Extension"] },
      { dayNumber: 4, exerciseNames: ["Incline Barbell Bench Press", "Machine Chest Press", "Dumbbell Shoulder Press", "Cable Fly", "Close Grip Bench Press"] },
      { dayNumber: 5, exerciseNames: ["Normal Grip Pulldown", "T-Bar Row", "Straight Arm Pulldown", "EZ Bar Curl", "Dumbbell Incline Curl"] },
      { dayNumber: 6, exerciseNames: ["Leg Press", "Barbell Stiff Leg Deadlift", "Hack Squat", "Seated Leg Curl", "Hip Abduction Machine"] },
    ],
  },
  {
    name: "Full Body 3-Day",
    mesoType: 3,
    days: [
      { dayNumber: 1, exerciseNames: ["High Bar Squat", "Medium Grip Bench Press", "Barbell Bent Over Row", "Barbell Curl", "Lying Leg Curl"] },
      { dayNumber: 2, exerciseNames: ["Leg Press", "Standing Barbell Shoulder Press", "Normal Grip Pulldown", "Cable Tricep Pushdown", "Barbell Hip Thrust"] },
      { dayNumber: 3, exerciseNames: ["Front Squat", "Incline Barbell Bench Press", "Seated Cable Row", "EZ Bar Curl", "Barbell Romanian Deadlift"] },
    ],
  },
  {
    name: "Upper/Lower 6-Day",
    mesoType: 6,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Barbell Bent Over Row", "Standing Barbell Shoulder Press", "Cable Curl", "Cable Tricep Pushdown"] },
      { dayNumber: 2, exerciseNames: ["High Bar Squat", "Lying Leg Curl", "Barbell Hip Thrust", "Leg Extension", "Cable Pull Through"] },
      { dayNumber: 3, exerciseNames: ["Incline Barbell Bench Press", "Normal Grip Pulldown", "Cable Lateral Raise", "Barbell Curl", "Close Grip Bench Press"] },
      { dayNumber: 4, exerciseNames: ["Leg Press", "Barbell Romanian Deadlift", "Seated Leg Curl", "Hack Squat", "Hip Abduction Machine"] },
      { dayNumber: 5, exerciseNames: ["Machine Chest Press", "Seated Cable Row", "Dumbbell Shoulder Press", "EZ Bar Curl", "Cable Overhead Tricep Extension"] },
      { dayNumber: 6, exerciseNames: ["Front Squat", "Barbell Stiff Leg Deadlift", "Leg Extension", "Glute Ham Raise", "Cable Pull Through"] },
    ],
  },
  {
    name: "Push/Pull/Legs 3-Day",
    mesoType: 3,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Incline Barbell Bench Press", "Standing Barbell Shoulder Press", "Cable Lateral Raise", "Cable Tricep Pushdown"] },
      { dayNumber: 2, exerciseNames: ["Barbell Bent Over Row", "Normal Grip Pulldown", "Seated Cable Row", "Barbell Curl", "Dumbbell Hammer Curl"] },
      { dayNumber: 3, exerciseNames: ["High Bar Squat", "Barbell Romanian Deadlift", "Leg Press", "Lying Leg Curl", "Leg Extension"] },
    ],
  },
  {
    name: "Bro Split 5-Day",
    mesoType: 5,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Incline Barbell Bench Press", "Cable Fly", "Pec Deck Machine"] },
      { dayNumber: 2, exerciseNames: ["Barbell Bent Over Row", "Normal Grip Pulldown", "Seated Cable Row", "Straight Arm Pulldown"] },
      { dayNumber: 3, exerciseNames: ["Standing Barbell Shoulder Press", "Cable Lateral Raise", "Machine Lateral Raise", "Cable Tricep Pushdown", "Close Grip Bench Press"] },
      { dayNumber: 4, exerciseNames: ["High Bar Squat", "Leg Press", "Leg Extension", "Lying Leg Curl", "Seated Leg Curl"] },
      { dayNumber: 5, exerciseNames: ["Barbell Curl", "EZ Bar Curl", "Dumbbell Hammer Curl", "Cable Overhead Tricep Extension", "Dumbbell Overhead Tricep Extension"] },
    ],
  },
];
