export interface ExerciseSeed {
  name: string;
  category: string;
  equipment: string;
  defaultVideoUrl: string | null;
}

export interface TemplateSeed {
  name: string;
  mesoType: number;
  days: { dayNumber: number; exerciseNames: string[] }[];
}

export const exercises: ExerciseSeed[] = [
  { name: "High Bar Squat", category: "QUADS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/i7J5h7BJ07g" },
  { name: "Leg Press", category: "QUADS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/B6rGDcfyPto" },
  { name: "Hack Squat", category: "QUADS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/4cxt_Tldugw" },
  { name: "Leg Extension", category: "QUADS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/m0FOpMEgero" },
  { name: "Front Squat", category: "QUADS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/v-mQm_droHg" },
  { name: "Dumbbell Goblet Squat", category: "QUADS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/lrqtGXD32FA" },
  { name: "Dumbbell Bulgarian Split Squat", category: "QUADS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/jNihW0WDIL4" },
  { name: "Dumbbell Lunges", category: "QUADS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/Z6R8A5tcrTc" },
  { name: "Bodyweight Sissy Squat", category: "QUADS", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/60gZOXu5gcQ" },
  { name: "Dumbbell Step Ups", category: "QUADS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/2IQvPmidQOo" },
  { name: "Barbell Hip Thrust", category: "GLUTES", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/xDmFkJxPzeM" },
  { name: "Barbell Romanian Deadlift", category: "GLUTES", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/_oyxCn2iSjU" },
  { name: "Cable Pull Through", category: "GLUTES", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/pv8e6OSyETE" },
  { name: "Hip Abduction Machine", category: "GLUTES", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/3ryh7PNhz3E" },
  { name: "Dumbbell Hip Thrust", category: "GLUTES", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/xDmFkJxPzeM" },
  { name: "Dumbbell Romanian Deadlift", category: "GLUTES", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/_oyxCn2iSjU" },
  { name: "Bodyweight Glute Bridge", category: "GLUTES", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/xDmFkJxPzeM" },
  { name: "Dumbbell Sumo Deadlift", category: "GLUTES", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/pfSMst14EFk" },
  { name: "Lying Leg Curl", category: "HAMSTRINGS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/PXG69tKDHoc" },
  { name: "Seated Leg Curl", category: "HAMSTRINGS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/PXG69tKDHoc" },
  { name: "Barbell Stiff Leg Deadlift", category: "HAMSTRINGS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/ysMo_VFN-dY" },
  { name: "Glute Ham Raise", category: "HAMSTRINGS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/Xg9B6pqHUQE" },
  { name: "Dumbbell Stiff Leg Deadlift", category: "HAMSTRINGS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/ysMo_VFN-dY" },
  { name: "Dumbbell Single Leg Deadlift", category: "HAMSTRINGS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/_oyxCn2iSjU" },
  { name: "Bodyweight Nordic Curl", category: "HAMSTRINGS", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/f5A-FKn0s8Q" },
  { name: "Dumbbell Lying Leg Curl", category: "HAMSTRINGS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/PXG69tKDHoc" },
  { name: "Medium Grip Bench Press", category: "HORIZONTAL PUSH", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/A0NBCkpYatQ" },
  { name: "Machine Chest Press", category: "HORIZONTAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/B-zyH8OTlsg" },
  { name: "Cable Fly", category: "HORIZONTAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/PRw7ieDBLl4" },
  { name: "Pec Deck Machine", category: "HORIZONTAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/O-OBCfyh9Fw" },
  { name: "Dumbbell Flat Bench Press", category: "HORIZONTAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/VmB1G1K7v94" },
  { name: "Dumbbell Fly", category: "HORIZONTAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/eozdVDA78K0" },
  { name: "Bodyweight Push Up", category: "HORIZONTAL PUSH", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/IODxDxX7oi4" },
  { name: "Dumbbell Squeeze Press", category: "HORIZONTAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/DIzziGJI0nk" },
  { name: "Smith Machine Bench Press", category: "HORIZONTAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/FsKAdOCFZkM" },
  { name: "Incline Barbell Bench Press", category: "INCLINE PUSH", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/0H0dZ-yP7XU" },
  { name: "Incline Machine Press", category: "INCLINE PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/PbROfDSbK4s" },
  { name: "Low to High Cable Fly", category: "INCLINE PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/Iwe6AmxVf7o" },
  { name: "Dumbbell Incline Bench Press", category: "INCLINE PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/kydayEMT-LQ" },
  { name: "Dumbbell Incline Fly", category: "INCLINE PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/bDaIL_wFcuo" },
  { name: "Bodyweight Incline Push Up", category: "INCLINE PUSH", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/cfns5VDVVvk" },
  { name: "Standing Barbell Shoulder Press", category: "VERTICAL PUSH", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/GGpArq725ls" },
  { name: "Seated Barbell Shoulder Press", category: "VERTICAL PUSH", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/GGpArq725ls" },
  { name: "Machine Shoulder Press", category: "VERTICAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/Wqq43dKnIBs" },
  { name: "Machine Lateral Raise", category: "VERTICAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/FeJP4E4Z-PY" },
  { name: "Cable Lateral Raise", category: "VERTICAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/PPrzBWZDOhA" },
  { name: "Dumbbell Shoulder Press", category: "VERTICAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/qEwKCR5JCog" },
  { name: "Dumbbell Lateral Raise", category: "VERTICAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/OuG1smZTsQQ" },
  { name: "Dumbbell Arnold Press", category: "VERTICAL PUSH", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/6Z15_WdXmVw" },
  { name: "Bodyweight Pike Push Up", category: "VERTICAL PUSH", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/sposDXWEB0A" },
  { name: "Barbell Bent Over Row", category: "HORIZONTAL BACK", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/G8lXvS0nUSQ" },
  { name: "Seated Cable Row", category: "HORIZONTAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/GZbfZ033f74" },
  { name: "T-Bar Row", category: "HORIZONTAL BACK", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/G8lXvS0nUSQ" },
  { name: "Machine Row", category: "HORIZONTAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/GZbfZ033f74" },
  { name: "Chest Supported Row Machine", category: "HORIZONTAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/0UBJ1m_bZjg" },
  { name: "Dumbbell Single Arm Row", category: "HORIZONTAL BACK", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/pYcpY20QaE8" },
  { name: "Dumbbell Bent Over Row", category: "HORIZONTAL BACK", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/G8lXvS0nUSQ" },
  { name: "Bodyweight Inverted Row", category: "HORIZONTAL BACK", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/hXTc1mDnNCw" },
  { name: "Dumbbell Seal Row", category: "HORIZONTAL BACK", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/pYcpY20QaE8" },
  { name: "Normal Grip Pulldown", category: "VERTICAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/VwtzEivlNwg" },
  { name: "Wide Grip Pulldown", category: "VERTICAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/VwtzEivlNwg" },
  { name: "Close Grip Pulldown", category: "VERTICAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/VwtzEivlNwg" },
  { name: "Straight Arm Pulldown", category: "VERTICAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/GZbfZ033f74" },
  { name: "Bodyweight Pull Up", category: "VERTICAL BACK", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/Hyrk8sSHTkk" },
  { name: "Bodyweight Chin Up", category: "VERTICAL BACK", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/Hyrk8sSHTkk" },
  { name: "Dumbbell Pullover", category: "VERTICAL BACK", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/VwtzEivlNwg" },
  { name: "Bodyweight Lat Pulldown (Band)", category: "VERTICAL BACK", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/VwtzEivlNwg" },
  { name: "Barbell Curl", category: "BICEPS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/5szOHT8cPns" },
  { name: "EZ Bar Curl", category: "BICEPS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/5szOHT8cPns" },
  { name: "Cable Curl", category: "BICEPS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/5szOHT8cPns" },
  { name: "Preacher Curl Machine", category: "BICEPS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/fIWP-FRFNU0" },
  { name: "Dumbbell Bicep Curl", category: "BICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/in7PaeYlhrM" },
  { name: "Dumbbell Hammer Curl", category: "BICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/in7PaeYlhrM" },
  { name: "Dumbbell Incline Curl", category: "BICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/soxrZlIl35U" },
  { name: "Dumbbell Concentration Curl", category: "BICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/Jvj2wV0vOYU" },
  { name: "Close Grip Bench Press", category: "TRICEPS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/A0NBCkpYatQ" },
  { name: "Cable Tricep Pushdown", category: "TRICEPS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/2-LAMcpzODU" },
  { name: "Cable Overhead Tricep Extension", category: "TRICEPS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/2-LAMcpzODU" },
  { name: "Tricep Dip Machine", category: "TRICEPS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/2z8JmcrW-As" },
  { name: "Dumbbell Overhead Tricep Extension", category: "TRICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/ozVrpOfstxE" },
  { name: "Dumbbell Skull Crusher", category: "TRICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/ozVrpOfstxE" },
  { name: "Dumbbell Kickback", category: "TRICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/ozVrpOfstxE" },
  { name: "Bodyweight Diamond Push Up", category: "TRICEPS", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/IODxDxX7oi4" },
  { name: "Dips", category: "TRICEPS", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/2z8JmcrW-As" },
  { name: "Calves on Leg Press", category: "CALVES", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/-qQv_HlKlu8" },
  { name: "Single Leg Dumbbell Calf Raise", category: "CALVES", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/-qQv_HlKlu8" },
  { name: "Standing Calf Raise", category: "CALVES", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/-qQv_HlKlu8" },
  { name: "Seated Calf Raise", category: "CALVES", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/-qQv_HlKlu8" },
  { name: "Barbell Shrug", category: "TRAPS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/cJRVVxmytaM" },
  { name: "Dumbbell Shrug", category: "TRAPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/cJRVVxmytaM" },
  { name: "Cable Facepull", category: "REAR DELTS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/V8d6XqDMcHA" },
  { name: "Dumbbell Rear Lateral Raise", category: "REAR DELTS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/EA7u4Q_8HQ0" },
  { name: "Reverse Pec Deck", category: "REAR DELTS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/5YK4bgzXDp0" },
  { name: "Machine Crunch", category: "ABS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/2RrGnjxSsiA" },
  { name: "Cable Crunch", category: "ABS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/9r4p-Lj9kzY" },
  { name: "Hanging Leg Raise", category: "ABS", equipment: "BODYWEIGHT", defaultVideoUrl: "https://youtu.be/2RrGnjxSsiA" },
  { name: "Conventional Deadlift", category: "GLUTES", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/AweC3UaM14o" },
  { name: "Sumo Deadlift", category: "GLUTES", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/pfSMst14EFk" },
  { name: "Barbell Walking Lunge", category: "QUADS", equipment: "BARBELL", defaultVideoUrl: "https://youtu.be/eFWCn5iEbTU" },
  { name: "45 Degree Back Raise", category: "HAMSTRINGS", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/5_ejbGfdAQE" },
  { name: "Underhand Pulldown", category: "VERTICAL BACK", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/VwtzEivlNwg" },
  { name: "Cable Upright Row", category: "VERTICAL PUSH", equipment: "MACHINE", defaultVideoUrl: "https://youtu.be/um3VVzqunPU" },
  { name: "Dumbbell Twist Curl", category: "BICEPS", equipment: "DUMBBELL", defaultVideoUrl: "https://youtu.be/in7PaeYlhrM" },
];

export const templates: TemplateSeed[] = [
  {
    name: "The Thor Specialization",
    mesoType: 5,
    days: [
      { dayNumber: 1, exerciseNames: ["Incline Barbell Bench Press", "Dumbbell Fly", "Barbell Bent Over Row", "Normal Grip Pulldown"] },
      { dayNumber: 2, exerciseNames: ["Standing Barbell Shoulder Press", "Dumbbell Lateral Raise", "Dumbbell Skull Crusher", "Dumbbell Hammer Curl"] },
      { dayNumber: 3, exerciseNames: ["High Bar Squat", "Leg Press", "Seated Leg Curl", "Calves on Leg Press"] },
      { dayNumber: 4, exerciseNames: ["Cable Fly", "Underhand Pulldown", "Cable Upright Row", "Cable Tricep Pushdown", "Barbell Curl"] },
      { dayNumber: 5, exerciseNames: ["Dumbbell Lateral Raise", "Barbell Shrug", "Dumbbell Twist Curl", "Dips"] },
    ],
  },
  {
    name: "The Valkyrie (Glute Specialization)",
    mesoType: 5,
    days: [
      { dayNumber: 1, exerciseNames: ["Conventional Deadlift", "Barbell Walking Lunge", "Dumbbell Hip Thrust", "Seated Leg Curl"] },
      { dayNumber: 2, exerciseNames: ["Medium Grip Bench Press", "Normal Grip Pulldown", "Standing Barbell Shoulder Press", "Bodyweight Push Up"] },
      { dayNumber: 3, exerciseNames: ["Hack Squat", "Dumbbell Bulgarian Split Squat", "45 Degree Back Raise", "Machine Crunch"] },
      { dayNumber: 4, exerciseNames: ["Seated Cable Row", "Cable Facepull", "Dumbbell Lateral Raise", "Dumbbell Rear Lateral Raise"] },
      { dayNumber: 5, exerciseNames: ["Sumo Deadlift", "Leg Press", "Lying Leg Curl", "Single Leg Dumbbell Calf Raise"] },
    ],
  },
  {
    name: "Arnold Split 6-Day",
    mesoType: 6,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Incline Barbell Bench Press", "Cable Fly", "Barbell Bent Over Row", "Normal Grip Pulldown"] },
      { dayNumber: 2, exerciseNames: ["Standing Barbell Shoulder Press", "Cable Lateral Raise", "Barbell Curl", "Cable Tricep Pushdown", "EZ Bar Curl"] },
      { dayNumber: 3, exerciseNames: ["High Bar Squat", "Leg Press", "Barbell Romanian Deadlift", "Lying Leg Curl", "Leg Extension"] },
      { dayNumber: 4, exerciseNames: ["Incline Barbell Bench Press", "Machine Chest Press", "Pec Deck Machine", "Seated Cable Row", "T-Bar Row"] },
      { dayNumber: 5, exerciseNames: ["Dumbbell Shoulder Press", "Machine Lateral Raise", "Dumbbell Hammer Curl", "Cable Overhead Tricep Extension", "Dumbbell Incline Curl"] },
      { dayNumber: 6, exerciseNames: ["Front Squat", "Hack Squat", "Barbell Stiff Leg Deadlift", "Seated Leg Curl", "Hip Abduction Machine"] },
    ],
  },
  {
    name: "Upper/Lower 4-Day",
    mesoType: 4,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Barbell Bent Over Row", "Dumbbell Shoulder Press", "Cable Curl", "Cable Tricep Pushdown"] },
      { dayNumber: 2, exerciseNames: ["High Bar Squat", "Lying Leg Curl", "Barbell Hip Thrust", "Leg Extension", "Standing Barbell Shoulder Press"] },
      { dayNumber: 3, exerciseNames: ["Incline Barbell Bench Press", "Normal Grip Pulldown", "Cable Fly", "EZ Bar Curl", "Cable Overhead Tricep Extension"] },
      { dayNumber: 4, exerciseNames: ["Leg Press", "Barbell Romanian Deadlift", "Seated Leg Curl", "Hip Abduction Machine", "Leg Extension"] },
    ],
  },
  {
    name: "Push/Pull/Legs 6-Day",
    mesoType: 6,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Incline Barbell Bench Press", "Standing Barbell Shoulder Press", "Cable Lateral Raise", "Cable Tricep Pushdown"] },
      { dayNumber: 2, exerciseNames: ["Barbell Bent Over Row", "Normal Grip Pulldown", "Seated Cable Row", "Barbell Curl", "Dumbbell Hammer Curl"] },
      { dayNumber: 3, exerciseNames: ["High Bar Squat", "Barbell Romanian Deadlift", "Leg Press", "Lying Leg Curl", "Leg Extension"] },
      { dayNumber: 4, exerciseNames: ["Incline Barbell Bench Press", "Machine Chest Press", "Dumbbell Shoulder Press", "Cable Fly", "Close Grip Bench Press"] },
      { dayNumber: 5, exerciseNames: ["Normal Grip Pulldown", "T-Bar Row", "Straight Arm Pulldown", "EZ Bar Curl", "Dumbbell Incline Curl"] },
      { dayNumber: 6, exerciseNames: ["Leg Press", "Barbell Stiff Leg Deadlift", "Hack Squat", "Seated Leg Curl", "Hip Abduction Machine"] },
    ],
  },
  {
    name: "Full Body 3-Day",
    mesoType: 3,
    days: [
      { dayNumber: 1, exerciseNames: ["High Bar Squat", "Medium Grip Bench Press", "Barbell Bent Over Row", "Barbell Curl", "Lying Leg Curl"] },
      { dayNumber: 2, exerciseNames: ["Leg Press", "Standing Barbell Shoulder Press", "Normal Grip Pulldown", "Cable Tricep Pushdown", "Barbell Hip Thrust"] },
      { dayNumber: 3, exerciseNames: ["Front Squat", "Incline Barbell Bench Press", "Seated Cable Row", "EZ Bar Curl", "Barbell Romanian Deadlift"] },
    ],
  },
  {
    name: "Upper/Lower 6-Day",
    mesoType: 6,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Barbell Bent Over Row", "Standing Barbell Shoulder Press", "Cable Curl", "Cable Tricep Pushdown"] },
      { dayNumber: 2, exerciseNames: ["High Bar Squat", "Lying Leg Curl", "Barbell Hip Thrust", "Leg Extension", "Cable Pull Through"] },
      { dayNumber: 3, exerciseNames: ["Incline Barbell Bench Press", "Normal Grip Pulldown", "Cable Lateral Raise", "Barbell Curl", "Close Grip Bench Press"] },
      { dayNumber: 4, exerciseNames: ["Leg Press", "Barbell Romanian Deadlift", "Seated Leg Curl", "Hack Squat", "Hip Abduction Machine"] },
      { dayNumber: 5, exerciseNames: ["Machine Chest Press", "Seated Cable Row", "Dumbbell Shoulder Press", "EZ Bar Curl", "Cable Overhead Tricep Extension"] },
      { dayNumber: 6, exerciseNames: ["Front Squat", "Barbell Stiff Leg Deadlift", "Leg Extension", "Glute Ham Raise", "Cable Pull Through"] },
    ],
  },
  {
    name: "Push/Pull/Legs 3-Day",
    mesoType: 3,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Incline Barbell Bench Press", "Standing Barbell Shoulder Press", "Cable Lateral Raise", "Cable Tricep Pushdown"] },
      { dayNumber: 2, exerciseNames: ["Barbell Bent Over Row", "Normal Grip Pulldown", "Seated Cable Row", "Barbell Curl", "Dumbbell Hammer Curl"] },
      { dayNumber: 3, exerciseNames: ["High Bar Squat", "Barbell Romanian Deadlift", "Leg Press", "Lying Leg Curl", "Leg Extension"] },
    ],
  },
  {
    name: "Bro Split 5-Day",
    mesoType: 5,
    days: [
      { dayNumber: 1, exerciseNames: ["Medium Grip Bench Press", "Incline Barbell Bench Press", "Cable Fly", "Pec Deck Machine"] },
      { dayNumber: 2, exerciseNames: ["Barbell Bent Over Row", "Normal Grip Pulldown", "Seated Cable Row", "Straight Arm Pulldown"] },
      { dayNumber: 3, exerciseNames: ["Standing Barbell Shoulder Press", "Cable Lateral Raise", "Machine Lateral Raise", "Cable Tricep Pushdown", "Close Grip Bench Press"] },
      { dayNumber: 4, exerciseNames: ["High Bar Squat", "Leg Press", "Leg Extension", "Lying Leg Curl", "Seated Leg Curl"] },
      { dayNumber: 5, exerciseNames: ["Barbell Curl", "EZ Bar Curl", "Dumbbell Hammer Curl", "Cable Overhead Tricep Extension", "Dumbbell Overhead Tricep Extension"] },
    ],
  },
];
